### PR TITLE
api to retrieve identity provider by type

### PR DESCRIPTION
**Pull request by avinashsingh2**
added API for retrieving identity provider by type.

### CODE REVIEW

**Comment by avinashsingh2** [comment]
thanks @mooreds!

**Comment by robotdan** [comment]
Thanks @avinashsingh2 - appreciate the contribution!

**Comment by mooreds** [comment]
@robotdan did you test this out? I had to add an import to src/main/java/io/fusionauth/client/FusionAuthClient.java in https://github.com/fusionauth/fusionauth-java-client to get it to compile:

```
import io.fusionauth.domain.provider.IdentityProviderType;
```

No issues with golang or netcore, they compiled just fine.

**Comment by robotdan** [comment]
I did, I have that change locally - it will go up with my next push to master.

**Comment by avinashsingh2** [comment]
Thanks, @robotdan

**Pull request merged**
