### PR TITLE
feat: go: implements stringer interface for enums.

### PR DESCRIPTION
**Pull request by matthewhartstonge**
Being a lazy developer plugging into other systems (i.e. terraform) I want to be able to get string representations of enums, and IDE autocomplete using:
```go
fusionauth.GrantType_ClientCredentials.String()
```

Instead of having to manually typecast every enum:
```go
string(fusionauth.GrantType_ClientCredentials)
```

This will also enable being able to be a bit more smart enum based functions by being able to cast enums to the Stringer interface to do things over multiple types. As a trivial example:

```go
package main

import (
	"fmt"
	"strings"
)

type EventType string

func (e EventType) String() string {
	return string(e)
}

const (
	// ...
	EventType_UserUpdate                     EventType = "user.update"
	EventType_UserUpdateComplete             EventType = "user.update.complete"
	EventType_Test                           EventType = "test"
)

func enumsToStringList(enums ...fmt.Stringer) string {
	var enumStrArr []string
	for _, enum := range enums {
		enumStrArr = append(enumStrArr, enum.String())
	}

	return strings.Join(enumStrArr, ", ")
}

func main() {
	eventsList := enumsToStringList(
		EventType_UserUpdate,
		EventType_UserUpdateComplete,
		EventType_Test,
	)
	fmt.Printf("Enabled events: %s", eventsList)
}
```

_started from: https://github.com/FusionAuth/go-client/pull/59_

### CODE REVIEW

**Comment by mooreds** [comment]
Thanks for the PR, @matthewhartstonge  This looks quite go-ish ( included in the go tour https://tour.golang.org/methods/18 for example ). 

Can you please add a test ( https://github.com/FusionAuth/go-client/blob/master/pkg/fusionauth/Client_test.go or https://github.com/FusionAuth/go-client/blob/master/pkg/fusionauth/Domain_test.go are the right places).

**Comment by matthewhartstonge** [comment]
Hey @mooreds, i'm wondering if it might be better to generate the tests programmatically for this?

Otherwise you may need to manually maintain a list of enums to iterate over and test for interface conformance.

i.e.

```go
// domain_test.go
import "testing"

func Test_{$d.type}ImplementsStringer(t *testing.T) {
  enum := &
  if _, ok := ${d.type}.(fmt.Stringer); !ok {
    t.Errorf("%s does not implement stringer interface", ${d.type})
  }
}
```

**Comment by mooreds** [comment]
Good point. I'll take a look at using something like what you suggested.

**Comment by robotdan** [comment]
Approved https://github.com/FusionAuth/fusionauth-client-builder/pull/42#pullrequestreview-845159138

**Pull request merged**
