### PR TITLE
correction on userComment success response

### PR DESCRIPTION
**Pull request by alex-fusionauth**
Correcting response type fixes this for TS.

image

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205328323177734

### CODE REVIEW

**Comment by lyleschemmerling** [comment]
Unfortunately this is modifying generated code which will get overwritten on the next pass.

The spot that needs edited is [here](https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/api/commentOnUser.json#L8)

**Comment by lyleschemmerling** [comment]
That may or may not wind up being the exact same diff as this, however, so we should leave this PR open but lets ensure that the json gets updated before we merge this.

**Review by lyleschemmerling — CHANGES_REQUESTED** [review]
pending update of client-builder

**Comment by mooreds** [comment]
Isn't this updating client-builder?

@lyleschemmerling what am I missing?

**Review by robotdan — APPROVED** [review]

**Pull request merged**
