### PR TITLE
Update generated Go client to accept Context

### PR DESCRIPTION
**Pull request by Zac300**
Updates generated Go client to allow context.Context to optionally be provided by overloading functions to have WithContext equivalent with context.Context as the first parameter.  Context has been added following [Go's recommendation](https://pkg.go.dev/context) to not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx.

By allowing Context to be provided this allows caller many improvements, such as the ability to cancel requests and include outbound FusionAuth API requests in OpenTelemetery distributed tracing just to name a few.

### CODE REVIEW

**Comment by robotdan** [comment]
@mmanes is this something you can review?

**Review by mmanes — APPROVED** [review]
@robotdan These changes look good. The associated [PR](https://github.com/FusionAuth/go-client/pull/71) can be closed once we rebuild the Go client with these changes.

Thank you @Zac300 for your contributions!

**Review by robotdan — APPROVED** [review]

**Comment by robotdan** [comment]
Thanks @mmanes and @Zac300 !!

**Comment by robotdan** [comment]
Related commit 
- https://github.com/FusionAuth/go-client/commit/2cd0761a42e1b2f18bc2927649358b49b06379b9

**Pull request merged**
